# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Lint"

on:
  pull_request:
  push:

concurrency:
  group: lint-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

jobs:
  coding-standards:
    name: "Coding Standard"

    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.1"

      - name: "Validate Composer"
        run: "composer validate"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Coding Standard"
        run: "make cs"
